# Generated by Django 3.2 on 2021-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=10)),
                ('match_date', models.DateField()),
                ('players', models.ManyToManyField(to='club.Member')),
            ],
        ),
    ]
