# Generated by Django 3.2 on 2021-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('blue_goals', models.IntegerField(default=0)),
                ('white_goals', models.IntegerField(default=0)),
                ('teams', models.ManyToManyField(to='club.Team')),
            ],
        ),
    ]
