# Generated by Django 3.2 on 2022-01-11 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmember_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
