# Generated by Django 3.2 on 2021-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
