# Generated by Django 3.2 on 2021-12-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20211220_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(default='Reigate', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_in_team',
            field=models.BooleanField(default=False),
        ),
    ]
