# Generated by Django 3.2 on 2022-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20220111_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_time',
            new_name='kick_off',
        ),
        migrations.AddField(
            model_name='match',
            name='results_added',
            field=models.BooleanField(default=False),
        ),
    ]
