# Generated by Django 3.2 on 2022-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20211222_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='colour',
            field=models.CharField(choices=[('BL', 'Blues'), ('WH', 'Whites')], max_length=7),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='club.Member'),
        ),
    ]
