# Generated by Django 3.2 on 2022-01-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20220111_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='kick_off',
            new_name='time',
        ),
    ]
