# Generated by Django 3.2 on 2022-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_rename_kick_off_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='registrations_open',
            field=models.BooleanField(default=False),
        ),
    ]
