# Generated by Django 3.2 on 2022-01-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_match_registrations_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_fixture',
            field=models.BooleanField(default=False),
        ),
    ]
