# Generated by Django 3.2 on 2022-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_matchplayer_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='teams_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
