# Generated by Django 3.2 on 2022-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_match_teams_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
