# Generated by Django 3.2 on 2022-01-21 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_matchplayer_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 11, 9, 32, 690207)),
        ),
    ]
