# Generated by Django 3.2 on 2022-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_matchplayer_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
