# Generated by Django 3.2 on 2022-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_auto_20220124_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
