# Generated by Django 3.2 on 2022-01-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20220124_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='is_in_team',
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchplayer', to='club.match'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmember', to=settings.AUTH_USER_MODEL),
        ),
    ]
