# Generated by Django 3.2 on 2022-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_auto_20220127_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='staff',
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
